### ISSUE TITLE
ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by fretif** [fretif/pagure#19]
I am trying to install SPUD on a cluster environment and I got the error below : 

[ INFO ]  Install meson 0.58.1 (Python tool)
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    from setuptools import setup
  File "/home/xxxxx/softs/python-modules/gcc93/lib/python3.7/site-packages/setuptools-57.0.0-py3.7.egg/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/home/xxxxx/softs/python-modules/gcc93/lib/python3.7/site-packages/setuptools-57.0.0-py3.7.egg/setuptools/dist.py", line 38, in <module>
    from setuptools import windows_support
  File "/home/xxxxx/softs/python-modules/gcc93/lib/python3.7/site-packages/setuptools-57.0.0-py3.7.egg/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/home/xxxx/softs/python/gcc93/3.7/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
[ ABORT ] Abort with status error 1

**Comment by fretif** [comment]
This is a common error on Python compilation when the headers package libffi are missing. You have to ask your system administrator to install the package libffi-devel (for a CentOS distribution).
Then, you have to reinstall Python with the argument --force-reinstall=1
