### ISSUE TITLE
Installation of Xbeach in sequential version : No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by MathieuS34** [fretif/pagure#22]
make  all-recursive
make[1]: Entering directory `/nfs/home/soulayrolm/softs/src/xbeach'
Making all in src
make[2]: Entering directory `/nfs/home/soulayrolm/softs/src/xbeach/src'
Making all in xbeachlibrary
make[3]: Entering directory `/nfs/home/soulayrolm/softs/src/xbeach/src/xbeachlibrary'
echo "Build_Revision = '`svnversion ../..`'" > version.dat
svn: E155021: This client is too old to work with the working copy at
'/nfs/home/soulayrolm/softs/src/xbeach' (format 31).
You need to get a newer Subversion client. For more details, see
  http://subversion.apache.org/faq.html#working-copy-format-change

echo "Build_URL = '`svn info ../.. | grep -m 1 URL`'" >> version.dat
svn: E155021: This client is too old to work with the working copy at
'/nfs/home/soulayrolm/softs/src/xbeach' (format 31).
You need to get a newer Subversion client. For more details, see
  http://subversion.apache.org/faq.html#working-copy-format-change

echo "Build_Date = '`date`'" >> version.dat
../../scripts/generate.py
Traceback (most recent call last):
  File "../../scripts/generate.py", line 29, in <module>
    import mako.template
  File "/home/soulayrolm/softs/python-modules/gcc75/lib/python3.7/site-packages/Mako-1.2.0-py3.7.egg/mako/template.py", line 19, in <module>
    from mako import cache
  File "/home/soulayrolm/softs/python-modules/gcc75/lib/python3.7/site-packages/Mako-1.2.0-py3.7.egg/mako/cache.py", line 7, in <module>
    from mako import util
  File "/home/soulayrolm/softs/python-modules/gcc75/lib/python3.7/site-packages/Mako-1.2.0-py3.7.egg/mako/util.py", line 14, in <module>
    from .compat import importlib_metadata_get
  File "/home/soulayrolm/softs/python-modules/gcc75/lib/python3.7/site-packages/Mako-1.2.0-py3.7.egg/mako/compat.py", line 68, in <module>
    import importlib_metadata  # noqa
ModuleNotFoundError: No module named 'importlib_metadata'
make[3]: *** [spacedecl.inc] Error 1
make[3]: Leaving directory `/nfs/home/soulayrolm/softs/src/xbeach/src/xbeachlibrary'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/nfs/home/soulayrolm/softs/src/xbeach/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/nfs/home/soulayrolm/softs/src/xbeach'
make: *** [all] Error 2
[  ABORT  ] PAGURE aborted with status error 2

**Comment by MathieuS34** [comment]
With intel compiler 

compilation aborted for H5Exception.cpp (code 2)
make[2]: *** [H5Exception.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
[  ABORT  ] PAGURE aborted with status error 2
